// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0akmlHMcGJVvhxn88NfIPLjn7rPjEiOU',
    appId: '1:1000727123535:web:9bc8449af75e8b87ab3c3a',
    messagingSenderId: '1000727123535',
    projectId: 'gen-z-calendar',
    authDomain: 'gen-z-calendar.firebaseapp.com',
    storageBucket: 'gen-z-calendar.firebasestorage.app',
    measurementId: 'G-SY46GTN63P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkqogeU-fF8_28ok2ILsF-QzT7dFOXCqM',
    appId: '1:1000727123535:android:ee6c6acf554b7d17ab3c3a',
    messagingSenderId: '1000727123535',
    projectId: 'gen-z-calendar',
    storageBucket: 'gen-z-calendar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1xinHdjVxhitQGq5IB8iloGhAyqpH_SU',
    appId: '1:1000727123535:ios:cfc9b7c61f716af8ab3c3a',
    messagingSenderId: '1000727123535',
    projectId: 'gen-z-calendar',
    storageBucket: 'gen-z-calendar.firebasestorage.app',
    iosBundleId: 'com.example.genZCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1xinHdjVxhitQGq5IB8iloGhAyqpH_SU',
    appId: '1:1000727123535:ios:cfc9b7c61f716af8ab3c3a',
    messagingSenderId: '1000727123535',
    projectId: 'gen-z-calendar',
    storageBucket: 'gen-z-calendar.firebasestorage.app',
    iosBundleId: 'com.example.genZCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0akmlHMcGJVvhxn88NfIPLjn7rPjEiOU',
    appId: '1:1000727123535:web:ac03911fcad58fa7ab3c3a',
    messagingSenderId: '1000727123535',
    projectId: 'gen-z-calendar',
    authDomain: 'gen-z-calendar.firebaseapp.com',
    storageBucket: 'gen-z-calendar.firebasestorage.app',
    measurementId: 'G-YFHRM3NQHV',
  );

}