// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_j1DQGiYfc87lrCGb4ZPTbd4tz-66c8U',
    appId: '1:571914832172:web:8242ab930fc6c10f414489',
    messagingSenderId: '571914832172',
    projectId: 'gen-z-35474',
    authDomain: 'gen-z-35474.firebaseapp.com',
    storageBucket: 'gen-z-35474.firebasestorage.app',
    measurementId: 'G-DLWSFV54MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdQxZmu_rKHzPzpL7560y0OeqvTPDhyks',
    appId: '1:571914832172:android:8c064a313f970b40414489',
    messagingSenderId: '571914832172',
    projectId: 'gen-z-35474',
    storageBucket: 'gen-z-35474.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj0zp5UFEtZUgo6P_lEh7dzNPg7aKdRjU',
    appId: '1:571914832172:ios:3e40773e41e738f4414489',
    messagingSenderId: '571914832172',
    projectId: 'gen-z-35474',
    storageBucket: 'gen-z-35474.firebasestorage.app',
    iosBundleId: 'com.example.genZCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj0zp5UFEtZUgo6P_lEh7dzNPg7aKdRjU',
    appId: '1:571914832172:ios:3e40773e41e738f4414489',
    messagingSenderId: '571914832172',
    projectId: 'gen-z-35474',
    storageBucket: 'gen-z-35474.firebasestorage.app',
    iosBundleId: 'com.example.genZCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_j1DQGiYfc87lrCGb4ZPTbd4tz-66c8U',
    appId: '1:571914832172:web:4e909d0050d0a907414489',
    messagingSenderId: '571914832172',
    projectId: 'gen-z-35474',
    authDomain: 'gen-z-35474.firebaseapp.com',
    storageBucket: 'gen-z-35474.firebasestorage.app',
    measurementId: 'G-3BVNLFBZPB',
  );
}
